language:
  - cpp
  
before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install -qq valgrind
  
addons:
  sonarcloud:
    organization: "zeropointsix-github"
    token:
      secure: e5d186929de4c3d299603616a8239e71da8e1f91

script:
  - qmake
  - make
  - valgrind ./tests/tests
  - ./tests/tests
  
after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner
  
cache:
  directories:
    - '$HOME/.sonar/cache'
  
notifications:
email: false
